"""Fix model unique fields

Revision ID: d54495220e50
Revises: b9d810e1e88d
Create Date: 2025-07-08 21:25:25.688636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54495220e50'
down_revision: Union[str, Sequence[str], None] = 'b9d810e1e88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Appointment_doctor_id_key'), 'Appointment', type_='unique')
    op.drop_constraint(op.f('Appointment_start_time_key'), 'Appointment', type_='unique')
    op.create_unique_constraint('uq_doctor_start_time', 'Appointment', ['doctor_id', 'start_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_doctor_start_time', 'Appointment', type_='unique')
    op.create_unique_constraint(op.f('Appointment_start_time_key'), 'Appointment', ['start_time'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('Appointment_doctor_id_key'), 'Appointment', ['doctor_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
